import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:sendspace/core/data/models/dto/tables/posts.dart';
import 'package:sendspace/core/failures/failure.dart';
import 'package:sendspace/core/mixins/s3_bucket_mixin.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

abstract class PostService {
  Future<void> createPost({required PostsRow post, File? videoFile});

  Future<List<PostsRow>> getUserPosts();
}

class SupabasePostService extends PostService with S3BucketMixin {
  final SupabaseClient _client;

  SupabasePostService(this._client);

  String get bucketName => 'post_videos';
  String get tableName => 'posts';

  @override
  /// Creates a post and optionally uploads a video
  Future<void> createPost({required PostsRow post, File? videoFile}) async {
    try {
      final user = _client.auth.currentUser;
      if (user == null) {
        throw AuthException("User not authenticated");
      }

      String? videoUrl;
      if (videoFile != null) {
        videoUrl = await uploadObject(
          client: _client,
          bucketName: bucketName,
          file: videoFile,
          objectKey: generateObjectKeyFromSupabaseClient(_client),
        );
      }

      final json =
          post.toJson()
            ..['video_url'] = videoUrl
            ..['created_at'] = DateTime.now().toIso8601String()
            ..['user_id'] = user.id;

      // Remove ID if present, since it's auto-generated by the database
      json.remove('id');

      await _client.from(tableName).insert(json);
    } catch (e, st) {
      rethrow;
    }
  }

  @override
  Future<List<PostsRow>> getUserPosts() async {
    final userId = _client.auth.currentUser?.id;

    if (userId == null) {
      throw AuthFailure("User is not authenticated.");
    }

    try {
      final response = await _client
          .from(tableName)
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      return (response as List)
          .map((json) => PostsRow.fromJson(json as Map<String, dynamic>))
          .toList();
    } catch (e) {
      return Future.error(e);
    }
  }
}
