//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'climb_types.dart';
export 'follows.dart';
export 'posts.dart';
export 'profiles.dart';
export 'users.dart';

/// Date: 2025-09-22 22:13:30.435580
