//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Follows Table
class FollowsTable extends SupabaseTable<FollowsRow> {
  /// Table Name
  @override
  String get tableName => 'follows';

  /// Create a [FollowsRow] from the [data] provided
  @override
  FollowsRow createRow(Map<String, dynamic> data) => FollowsRow.fromJson(data);
}

/// Follows Row
class FollowsRow extends SupabaseDataRow {
  /// Follows Row
  FollowsRow({
    required String followerId,
    required String followedId,
    DateTime? followedAt,
  }) : super({
         'follower_id': supaSerialize(followerId),
         'followed_id': supaSerialize(followedId),
         if (followedAt != null) 'followed_at': supaSerialize(followedAt),
       });

  /// Follows Row
  const FollowsRow._(super.data);

  /// Create Follows Row from a [data] map
  factory FollowsRow.fromJson(Map<String, dynamic> data) =>
      FollowsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => FollowsTable();

  /// Follower Id field name
  static const String followerIdField = 'follower_id';

  /// Follower Id
  String get followerId => getField<String>(followerIdField)!;
  set followerId(String value) => setField<String>(followerIdField, value);

  /// Followed Id field name
  static const String followedIdField = 'followed_id';

  /// Followed Id
  String get followedId => getField<String>(followedIdField)!;
  set followedId(String value) => setField<String>(followedIdField, value);

  /// Followed At field name
  static const String followedAtField = 'followed_at';

  /// Followed At
  DateTime get followedAt =>
      getField<DateTime>(followedAtField, defaultValue: DateTime.now())!;
  set followedAt(DateTime value) => setField<DateTime>(followedAtField, value);

  /// Make a copy of the current [FollowsRow]
  /// overriding the provided fields
  FollowsRow copyWith({
    String? followerId,
    String? followedId,
    DateTime? followedAt,
  }) => FollowsRow.fromJson({
    'follower_id': supaSerialize(followerId) ?? data['follower_id'],
    'followed_id': supaSerialize(followedId) ?? data['followed_id'],
    'followed_at': supaSerialize(followedAt) ?? data['followed_at'],
  });
}

/// Date: 2025-09-22 22:13:30.429849
