//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Climb Types Table
class ClimbTypesTable extends SupabaseTable<ClimbTypesRow> {
  /// Table Name
  @override
  String get tableName => 'climb_types';

  /// Create a [ClimbTypesRow] from the [data] provided
  @override
  ClimbTypesRow createRow(Map<String, dynamic> data) =>
      ClimbTypesRow.fromJson(data);
}

/// Climb Types Row
class ClimbTypesRow extends SupabaseDataRow {
  /// Climb Types Row
  ClimbTypesRow({required String name, String? id, DateTime? createdAt})
    : super({
        'name': supaSerialize(name),
        if (id != null) 'id': supaSerialize(id),
        if (createdAt != null) 'created_at': supaSerialize(createdAt),
      });

  /// Climb Types Row
  const ClimbTypesRow._(super.data);

  /// Create Climb Types Row from a [data] map
  factory ClimbTypesRow.fromJson(Map<String, dynamic> data) =>
      ClimbTypesRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ClimbTypesTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String get name => getField<String>(nameField)!;
  set name(String value) => setField<String>(nameField, value);

  /// Make a copy of the current [ClimbTypesRow]
  /// overriding the provided fields
  ClimbTypesRow copyWith({String? name, String? id, DateTime? createdAt}) =>
      ClimbTypesRow.fromJson({
        'name': supaSerialize(name) ?? data['name'],
        'id': supaSerialize(id) ?? data['id'],
        'created_at': supaSerialize(createdAt) ?? data['created_at'],
      });
}

/// Date: 2025-08-05 23:44:48.433129
