//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'enums/_enums.dart';
export 'tables/_tables.dart';

/// Date: 2025-09-14 19:21:40.174619
