//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'location_type.dart';

/// Date: 2025-08-05 22:07:52.998456
