//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Location Type enum
enum LocationType {
  /// indoor
  indoor,

  /// outdoor
  outdoor,
}

/// Date: 2025-08-05 22:07:52.997196
